services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: lil_url
      POSTGRES_PASSWORD: lil_url_pass
      POSTGRES_DB: lil_url
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
